### ISSUE TITLE
agent.so?

### ISSUE THREAD

**Issue by kingty** [codematrixer/awesome-hdc#3]
hello ,agent.so 的源码可以学习下吗？

**Comment by codematrixer** [comment]
> hello ,agent.so 的源码可以学习下吗？

这是鸿蒙官方自动化框架hpyium提供的，我是阅读这个代码才发现的agent.so，这个动态库提供了UI操作，元素查找，屏幕录制等功能

**Comment by kingty** [comment]
奥，谢谢。我还以为是你自己实现了个agent。我看test框架里公开了两个接口

// hook function names of UiTestExtension library
#define UITEST_EXTENSION_CALLBACK_ONINIT "UiTestExtension_OnInit"
#define UITEST_EXTENSION_CALLBACK_ONRUN "UiTestExtension_OnRun"
理论上可以自己实现

**Comment by kingty** [comment]
在哪里可以找到agent.so,有链接吗？hpyium的代码里我没看到？

**Comment by codematrixer** [comment]
> 在哪里可以找到agent.so,有链接吗？hpyium的代码里我没看到？

https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V5/hypium-python-guidelines-V5

pip install xdevice-5.0.3.300.tar.gz
pip install xdevice-devicetest-5.0.3.300.tar.gz
pip install xdevice-ohos-5.0.3.300.tar.gz
pip install hypium-5.0.3.300.tar.gz
