### ISSUE TITLE
hdc 是否支持屏幕亮度设定？

### ISSUE THREAD

**Issue by edisonchan** [codematrixer/awesome-hdc#7]
在华为官方网站找不到相关信息。
然后在 forums.openharmony.cn 看到下面的内容：
https://forums.openharmony.cn/forum.php?mod=viewthread&tid=1092&extra=page%3D1&mobile=no
![image](https://github.com/user-attachments/assets/6383c0ce-d4d7-4916-aef1-d7760708cd58)

```
power-shell display -s 20
usage: power-shell
command list:
  setmode :    Set power mode.
  wakeup  :    Wakeup system and turn screen on.
  suspend :    Suspend system and turn screen off.
  timeout :    Override or Restore screen off time.
  help    :    Show this help menu.
```
实测不行，可能是因为我的设备是鸿蒙 Next 设备？抑或这个指令本身已经废弃了？

**Comment by codematrixer** [comment]
> 在华为官方网站找不到相关信息。 然后在 forums.openharmony.cn 看到下面的内容： https://forums.openharmony.cn/forum.php?mod=viewthread&tid=1092&extra=page%3D1&mobile=no ![image](https://private-user-images.githubusercontent.com/8596506/369658416-6383c0ce-d4d7-4916-aef1-d7760708cd58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzQ4NzYsIm5iZiI6MTcyNzA3NDU3NiwicGF0aCI6Ii84NTk2NTA2LzM2OTY1ODQxNi02MzgzYzBjZS1kNGQ3LTQ5MTYtYWVmMS1kNzc2MDcwOGNkNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDY1NjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMzMTNkNWRjMDY0OTY1Mzg5MTE2NjIzMDAyNjQ2MDNiNzhhZTAzNmJmNzJjN2QyMWEyYTQ5MDY0ZjgxMmI1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lPiq1KS1wT7uO-lY_1SyAUK4x35Zqc9lYC_adqktvKs)
> 
> ```
> power-shell display -s 20
> usage: power-shell
> command list:
>   setmode :    Set power mode.
>   wakeup  :    Wakeup system and turn screen on.
>   suspend :    Suspend system and turn screen off.
>   timeout :    Override or Restore screen off time.
>   help    :    Show this help menu.
> ```
> 
> 实测不行，可能是因为我的设备是鸿蒙 Next 设备？抑或这个指令本身已经废弃了？

问了官方，目前并没有能设置屏幕亮度的hdc命令
