### ISSUE TITLE
hdc可以访问类似Android的sdcard上内容吗？如创建文件等等操作，目前我看到只能在/data/local/tmp目录下

### ISSUE THREAD

**Issue by lycfr** [codematrixer/awesome-hdc#8]
hdc可以访问类似Android的sdcard上内容吗？如创建文件等等操作，目前我看到只能在/data/local/tmp目录下

**Comment by codematrixer** [comment]
HarmonyOS NEXT 权限管控比较严格，hdc只能操作/data/local/tmp，应用内只能操作沙盒

**Comment by lycfr** [comment]
了解
