### ISSUE TITLE
hdc完整包是多大

### ISSUE THREAD

**Issue by guo-miantiao** [codematrixer/awesome-hdc#9]
你好，

我正在开发一个工具，需要集成 `hdc` 工具来实现日志抓取功能。我注意到 `hdc` 工具位于 `\command-line-tools\sdk\default\openharmony\toolchains` 目录下，该目录的总大小约为 30MB。相比之下，`adb` 工具的大小仅为 1.6MB。

为了减少最终工具的体积，我希望能够只打包 `hdc` 工具及其必需的依赖文件，而不是整个目录。具体来说，我需要实现日志抓取功能。

问题

1. 哪些文件是 `hdc` 工具运行所必需的
   - 特别是用于日志抓取功能的文件。
2. 是否有压缩版的 `hdc` 工具？
   - 如果有，能否提供下载链接或说明如何获取？
3. 是否有官方文档或指南，详细列出了 `hdc` 工具的依赖文件

目标
- 尽量减少打包后的工具体积。
- 确保 `hdc` 工具能够正常运行，特别是日志抓取功能。

环境
- 开发语言：python
- 目标平台：HarmonyOS Next

感谢！

**Comment by codematrixer** [comment]
我在 macOS 上大概试了下，toolchains目录下只需要hdc和libusb_shared.dylib两个文件就可以了。 一共4.7MB左右

<img width="472" alt="image" src="https://github.com/user-attachments/assets/be780321-520b-4468-85f7-73c560895d55">
